---
- name: Copy redirect.conf
  become: yes
  template:
    src: redirect.conf.j2
    dest: "{{ mailcow__install_path }}/data/conf/nginx/redirect.conf"
  when: mailcow__redirect_http_to_https

- name: Delete redirect.conf
  file:
    path: "{{ mailcow__install_path }}"/data/conf/nginx/redirect.conf"
    state: absent
  when: not mailcow__redirect_http_to_https
