---

- name: Restart mailcow
  become: yes
  shell: |
    docker-compose --project-name {{ mailcow__docker_compose_project_name }} restart
  args:
    chdir: "{{ mailcow__install_path }}"

- name: Recreate mailcow
  become: yes
  shell: |
    docker-compose --project-name {{ mailcow__docker_compose_project_name }} down
    docker-compose --project-name {{ mailcow__docker_compose_project_name }} up -d
  args:
    chdir: "{{ mailcow__install_path }}"

- name: Restart mailcow rspamd
  become: yes
  shell: docker-compose restart rspamd-mailcow
  args:
    chdir: "{{ mailcow__install_path }}"
